# Default values for Pelican Panel Helm Chart
# Leave settings that you dont know. Every change you need to make is documented.

general:
  domain: "https://pelican.domain.com" # Change to your domain.
  email: "email" # Change to the email you wanna use for lets encrypt certificates.
  debug: "false"
  behind_proxy: "true"
  trusted_proxies: "ip"

image:
  overwriteRepository: "" # Overwrites the repository for the container. Default is ghcr.io/pelican-dev/panel.
  overwriteTag: "" # Overwrites the container version. Default is v1.0.0-beta27.
  overwriteImagePullPolicy: "" # Overwrites the image pull policy. Default is IfNotPresent. IfNotPresent/Always/Never

service:
  type: "ClusterIP"
  port: 80

# These are only the pvc's. You still need to provides pv's.
volumes:
  sharedStorageClassName: "storageClassName"
  data:
    accessMode: "ReadWriteOnce"
    size: "1Gi"
    #overwriteStorageClassName: "" # Overwrites the sharedStorageClassName for this pvc. Uncomment to overwrite.
  logs:
    accessMode: "ReadWriteOnce"
    size: "1Gi" 
    #overwriteStorageClassName: "" # Overwrites the sharedStorageClassName for this pvc. Uncomment to overwrite.