apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-caddyfile"
data:
  caddyfile: |
    {
      admin {{ .Values.general.caddy.admin | default off }}
      servers {
        trusted_proxies static {{ .Values.general.caddy.trusted_proxies }}
      }
    }

    :80 {
      root * /var/www/html/public
      encode gzip

      php_fastcgi 127.0.0.1:9000 {
          env PHP_VALUE "upload_max_filesize = {{ .Values.general.caddy.upload_max_filesize | default 2 }}M
                         post_max_size = {{ .Values.general.caddy.post_max_size | default 8 }}M"
      }
      file_server
    }