apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      initContainers:
        - name: init-pelican-data
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              chown -R 82:82 /data-pv
              chown -R 82:82 /log-pv
              sleep 60
              cp -r /pelican-data/* /data-pv
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /data-pv
            - name: logs
              mountPath: /log-pv
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /pelican-data
            - name: logs
              mountPath: /var/www/html/storage/logs
            - name: caddyfile
              mountPath: /etc/caddy/Caddyfile
              subPath: caddyfile
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data"
        - name: logs
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-logs"
        - name: caddyfile
          configMap:
            name: "{{ .Release.Name }}-caddyfile"