apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository | default "ghcr.io/pelican-dev/panel" }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
          env:
            - name: APP_URL
              value: {{ .Values.general.domain | quote }}
            - name: LE_EMAIL
              value: {{ .Values.general.email | quote }}
            - name: APP_DEBUG
              value: {{ .Values.general.debug | quote }}
            - name: BEHIND_PROXY
              value: {{ .Values.general.behind_proxy | quote }}
            - name: TRUSTED_PROXIES
              value: {{ .Values.general.trusted_proxies | quote }}
          volumeMounts:
            - name: data
              mountPath: /pelican-data
            - name: logs
              mountPath: /var/www/html/storage/logs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data"
        - name: logs
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-logs"