apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-data"
spec:
  accessModes:
    - {{ .Values.volumes.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.data.size }}
  storageClassName: {{ .Values.volumes.data.storageClassName | default .Values.volumes.sharedStorageClassName }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-logs"
spec:
  accessModes:
    - {{ .Values.volumes.logs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.logs.size }}
  storageClassName: {{ .Values.volumes.logs.storageClassName | default .Values.volumes.sharedStorageClassName }}